modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "whiteout"
version = "1.5-forge-1.0.0"
displayName = "Cobblemon Whiteout"
description = '''
What if your player got KO'd when your Cobblemon team wiped out, like in the games?
'''

[[dependencies.whiteout]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.whiteout]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.whiteout]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.0,1.6.0)"
ordering = "NONE"
side = "BOTH"
